### PR TITLE
feat: added default expiry for pastes

### PR DESCRIPTION
**Pull request by alexraileanu**
added envvar to set which of the predefined values will be selected in the dropdown that set the expiry date. if none match or the envar is not set, it will default to -1 (no expiry). this is useful so that no paste lives forever in storage.

fixes (partially) #19

@Cesura let me know if there's anything you'd like me to add/change

### CODE REVIEW

**Review by xrh0905 — APPROVED** [review]
Great work! looking forward to it.

**Comment by catduckgnaf** [comment]
What are the variables? is it merged?

**Comment by xrh0905** [comment]
> What are the variables? is it merged?

Not merged yet, `PASTEY_DEFAULT_PASTE_EXPIRY`

**Comment by alexraileanu** [comment]
since this project looks abandoned, I have decided to maintain my own fork of it with these changes.

**Comment by catduckgnaf** [comment]
> since this project looks abandoned, I have decided to maintain my own fork of it with these changes.

Can you share with me when you have it complete?

**Comment by alexraileanu** [comment]
@catduckgnaf you can check the readme at [alexraileanu/pastey](https://github.com/alexraileanu/pastey). should be more or less usage as this. if you need help, feel free to open an issue in that repo. ty

**Pull request closed without merging**
