### PR TITLE
No more tensorflow and fixed requirements

### PR DESCRIPTION
**Pull request by irishgreencitrus**
I don't necessarily recommend merging this directly, apart from making sure that the requirements.txt has a ==version as this will install one version and not every version. This'll work now on raspberry pi 3 and 4. If i find a more lightweight language detection library i'll replace it here

### CODE REVIEW

**Comment by irishgreencitrus** [comment]
I'm going to work on a language detection from file extension, rather than just a blank guess. this is how github gists do it and many other things

**Comment by Cesura** [comment]
I can build an image that disables language detection, as there seems to be some interest. As for file extension detection, how does that work when the paste is submitted as form content?

**Comment by irishgreencitrus** [comment]
if you take the title of the paste, and split it at the `.`, titlesplit[0] will be the file name and titlesplit[1] will be the extension

**Comment by irishgreencitrus** [comment]
if you're talking about the piping to automatic paste creation, i'm not sure but calling every paste untitled seems like it could get very cluttered

**Comment by irishgreencitrus** [comment]
Is this still necessary? Or is there another way to do it now?

**Comment by Cesura** [comment]
If you've implemented a fallback mechanism based on file extension for when the model confidence is low, then I would happily merge that. But it's been over a year so I don't blame you if the interest is no longer there. :wink:

**Pull request closed without merging**
